import { Palette, PaletteName } from '../interface';

export const STATUS_LIGHT = {
  success: '#16a34a',
  warning: '#ca8a04',
  error: '#dc2626',
  info: '#2563eb',
};

export const STATUS_DARK = {
  success: '#4ade80',
  warning: '#facc15',
  error: '#f87171',
  info: '#60a5fa',
};

export const PALETTES: Record<PaletteName, Palette> = {
  ocean: {
    name: 'ocean',
    label: 'Ocean',
    description: 'Azul profundo y cyan. Fresco, técnico, confiable.',
    light: {
      primary: '#0369a1',
      onPrimary: '#ffffff',
      primaryContainer: '#e0f2fe',
      secondary: '#0891b2',
      onSecondary: '#ffffff',
      secondaryContainer: '#cffafe',
      background: '#f4faff',
      surface: '#e8f3fd',
      surfaceVariant: '#d6e8fa',
      text: '#0f172a',
      textMuted: '#5b748f',
      border: '#c3dcf3',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#38bdf8',
      onPrimary: '#0c4a6e',
      primaryContainer: '#075985',
      secondary: '#22d3ee',
      onSecondary: '#083344',
      secondaryContainer: '#155e75',
      background: '#0f172a',
      surface: '#1e293b',
      surfaceVariant: '#334155',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      border: '#334155',
      ...STATUS_DARK,
    },
  },
  forest: {
    name: 'forest',
    label: 'Forest',
    description: 'Verde natural con acento lima. Orgánico, sano, bienestar.',
    light: {
      primary: '#16a34a',
      onPrimary: '#ffffff',
      primaryContainer: '#dcfce7',
      secondary: '#65a30d',
      onSecondary: '#ffffff',
      secondaryContainer: '#ecfccb',
      background: '#f4fdf6',
      surface: '#e6f7ea',
      surfaceVariant: '#d4f0db',
      text: '#0f172a',
      textMuted: '#5d7a64',
      border: '#bfe6c9',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#4ade80',
      onPrimary: '#14532d',
      primaryContainer: '#15803d',
      secondary: '#a3e635',
      onSecondary: '#1a2e05',
      secondaryContainer: '#4d7c0f',
      background: '#0f172a',
      surface: '#1e293b',
      surfaceVariant: '#1f2e24',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      border: '#334155',
      ...STATUS_DARK,
    },
  },
  sunset: {
    name: 'sunset',
    label: 'Sunset',
    description: 'Naranja cálido con ámbar. Enérgico, motivador, cercano.',
    light: {
      primary: '#ea580c',
      onPrimary: '#ffffff',
      primaryContainer: '#ffedd5',
      secondary: '#f59e0b',
      onSecondary: '#ffffff',
      secondaryContainer: '#fef3c7',
      background: '#fffaf4',
      surface: '#fff1e3',
      surfaceVariant: '#ffe3c9',
      text: '#1c1917',
      textMuted: '#8a7256',
      border: '#f8d3ad',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#fb923c',
      onPrimary: '#7c2d12',
      primaryContainer: '#9a3412',
      secondary: '#fbbf24',
      onSecondary: '#451a03',
      secondaryContainer: '#b45309',
      background: '#1c1917',
      surface: '#292524',
      surfaceVariant: '#3f3b37',
      text: '#fafaf9',
      textMuted: '#a8a29e',
      border: '#44403c',
      ...STATUS_DARK,
    },
  },
  royal: {
    name: 'royal',
    label: 'Royal',
    description: 'Violeta con rosa. Creativo, premium, moderno.',
    light: {
      primary: '#7c3aed',
      onPrimary: '#ffffff',
      primaryContainer: '#ede9fe',
      secondary: '#ec4899',
      onSecondary: '#ffffff',
      secondaryContainer: '#fce7f3',
      background: '#fbf7ff',
      surface: '#f3e9fe',
      surfaceVariant: '#e9d8fc',
      text: '#1e1b4b',
      textMuted: '#6f6699',
      border: '#dcc4f7',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#a78bfa',
      onPrimary: '#4c1d95',
      primaryContainer: '#5b21b6',
      secondary: '#f472b6',
      onSecondary: '#831843',
      secondaryContainer: '#9f1239',
      background: '#1e1b4b',
      surface: '#312e81',
      surfaceVariant: '#3730a3',
      text: '#f5f3ff',
      textMuted: '#a5b4fc',
      border: '#4338ca',
      ...STATUS_DARK,
    },
  },
  slate: {
    name: 'slate',
    label: 'Slate',
    description: 'Gris neutro con acento azul. Profesional, sobrio, corporativo.',
    light: {
      primary: '#334155',
      onPrimary: '#ffffff',
      primaryContainer: '#e2e8f0',
      secondary: '#3b82f6',
      onSecondary: '#ffffff',
      secondaryContainer: '#dbeafe',
      background: '#f7f9fc',
      surface: '#eef2f8',
      surfaceVariant: '#e2e8f2',
      text: '#0f172a',
      textMuted: '#5b6b82',
      border: '#cfd8e6',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#cbd5e1',
      onPrimary: '#0f172a',
      primaryContainer: '#334155',
      secondary: '#60a5fa',
      onSecondary: '#0c2a6b',
      secondaryContainer: '#1e40af',
      background: '#020617',
      surface: '#0f172a',
      surfaceVariant: '#1e293b',
      text: '#f8fafc',
      textMuted: '#94a3b8',
      border: '#1e293b',
      ...STATUS_DARK,
    },
  },
  mono: {
    name: 'mono',
    label: 'Mono',
    description: 'Escala de grises pura. Minimalista, elegante, editorial.',
    light: {
      primary: '#18181b',
      onPrimary: '#fafafa',
      primaryContainer: '#e4e4e7',
      secondary: '#52525b',
      onSecondary: '#fafafa',
      secondaryContainer: '#d4d4d8',
      background: '#fafafa',
      surface: '#f4f4f5',
      surfaceVariant: '#e9e9ec',
      text: '#09090b',
      textMuted: '#71717a',
      border: '#dcdce0',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#fafafa',
      onPrimary: '#18181b',
      primaryContainer: '#27272a',
      secondary: '#d4d4d8',
      onSecondary: '#18181b',
      secondaryContainer: '#3f3f46',
      background: '#09090b',
      surface: '#18181b',
      surfaceVariant: '#27272a',
      text: '#fafafa',
      textMuted: '#a1a1aa',
      border: '#27272a',
      ...STATUS_DARK,
    },
  },
  crimson: {
    name: 'crimson',
    label: 'Crimson',
    description: 'Rojo carmesí con rosa. Audaz, apasionado, con urgencia.',
    light: {
      primary: '#dc2626',
      onPrimary: '#ffffff',
      primaryContainer: '#fee2e2',
      secondary: '#db2777',
      onSecondary: '#ffffff',
      secondaryContainer: '#fce7f3',
      background: '#fff6f6',
      surface: '#fde8e8',
      surfaceVariant: '#fbd8dc',
      text: '#1c1917',
      textMuted: '#8a6f6f',
      border: '#f3c0c6',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#fb7185',
      onPrimary: '#7f1d1d',
      primaryContainer: '#991b1b',
      secondary: '#f472b6',
      onSecondary: '#831843',
      secondaryContainer: '#9d174d',
      background: '#1c1917',
      surface: '#292524',
      surfaceVariant: '#44403c',
      text: '#fafaf9',
      textMuted: '#a8a29e',
      border: '#44403c',
      ...STATUS_DARK,
    },
  },
  teal: {
    name: 'teal',
    label: 'Teal',
    description: 'Verde azulado con esmeralda. Sereno, moderno, premium.',
    light: {
      primary: '#0d9488',
      onPrimary: '#ffffff',
      primaryContainer: '#ccfbf1',
      secondary: '#059669',
      onSecondary: '#ffffff',
      secondaryContainer: '#d1fae5',
      background: '#f2fdfb',
      surface: '#e2f7f2',
      surfaceVariant: '#caefe8',
      text: '#0f172a',
      textMuted: '#5a7a74',
      border: '#b3e3da',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#2dd4bf',
      onPrimary: '#042f2e',
      primaryContainer: '#0f766e',
      secondary: '#34d399',
      onSecondary: '#022c22',
      secondaryContainer: '#047857',
      background: '#0f172a',
      surface: '#1e293b',
      surfaceVariant: '#163832',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      border: '#334155',
      ...STATUS_DARK,
    },
  },
};

export const PALETTE_NAMES = Object.keys(PALETTES) as PaletteName[];
