import { Palette, PaletteName } from '../interface';

export const STATUS_LIGHT = {
  success: '#16a34a',
  warning: '#ca8a04',
  error: '#dc2626',
  info: '#2563eb',
};

export const STATUS_DARK = {
  success: '#4ade80',
  warning: '#facc15',
  error: '#f87171',
  info: '#60a5fa',
};

export const PALETTES: Record<PaletteName, Palette> = {
  ocean: {
    name: 'ocean',
    label: 'Finanzas',
    icon: 'finance',
    description:
      'Color seleccionado para apps de finanzas: cobros, billeteras, banca o fintech. Sus azules transmiten confianza y seguridad.',
    light: {
      primary: '#0369a1',
      onPrimary: '#ffffff',
      primaryContainer: '#e0f2fe',
      secondary: '#0891b2',
      onSecondary: '#ffffff',
      secondaryContainer: '#cffafe',
      background: '#f4faff',
      surface: '#e8f3fd',
      surfaceVariant: '#d6e8fa',
      text: '#0f172a',
      textMuted: '#5b748f',
      border: '#c3dcf3',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#38bdf8',
      onPrimary: '#0c4a6e',
      primaryContainer: '#075985',
      secondary: '#22d3ee',
      onSecondary: '#083344',
      secondaryContainer: '#155e75',
      background: '#0f172a',
      surface: '#1e293b',
      surfaceVariant: '#334155',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      border: '#334155',
      ...STATUS_DARK,
    },
  },
  forest: {
    name: 'forest',
    label: 'Gastronomía',
    icon: 'silverware-fork-knife',
    description:
      'Color seleccionado para apps de gastronomía: comida, recetas, restaurantes o productos orgánicos. Verdes frescos y naturales.',
    light: {
      primary: '#16a34a',
      onPrimary: '#ffffff',
      primaryContainer: '#dcfce7',
      secondary: '#65a30d',
      onSecondary: '#ffffff',
      secondaryContainer: '#ecfccb',
      background: '#f4fdf6',
      surface: '#e6f7ea',
      surfaceVariant: '#d4f0db',
      text: '#0f172a',
      textMuted: '#5d7a64',
      border: '#bfe6c9',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#4ade80',
      onPrimary: '#14532d',
      primaryContainer: '#15803d',
      secondary: '#a3e635',
      onSecondary: '#1a2e05',
      secondaryContainer: '#4d7c0f',
      background: '#0f172a',
      surface: '#1e293b',
      surfaceVariant: '#1f2e24',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      border: '#334155',
      ...STATUS_DARK,
    },
  },
  sunset: {
    name: 'sunset',
    label: 'Reparto',
    icon: 'moped',
    description:
      'Color seleccionado para apps de reparto: delivery, pedidos y logística de última milla. Naranjas cálidos que invitan a la acción.',
    light: {
      primary: '#ea580c',
      onPrimary: '#ffffff',
      primaryContainer: '#ffedd5',
      secondary: '#f59e0b',
      onSecondary: '#ffffff',
      secondaryContainer: '#fef3c7',
      background: '#fffaf4',
      surface: '#fff1e3',
      surfaceVariant: '#ffe3c9',
      text: '#1c1917',
      textMuted: '#8a7256',
      border: '#f8d3ad',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#fb923c',
      onPrimary: '#7c2d12',
      primaryContainer: '#9a3412',
      secondary: '#fbbf24',
      onSecondary: '#451a03',
      secondaryContainer: '#b45309',
      background: '#1c1917',
      surface: '#292524',
      surfaceVariant: '#3f3b37',
      text: '#fafaf9',
      textMuted: '#a8a29e',
      border: '#44403c',
      ...STATUS_DARK,
    },
  },
  royal: {
    name: 'royal',
    label: 'Estilo de vida',
    icon: 'hanger',
    description:
      'Color seleccionado para apps de estilo de vida: moda, belleza y contenido aspiracional. Violetas premium y creativos.',
    light: {
      primary: '#7c3aed',
      onPrimary: '#ffffff',
      primaryContainer: '#ede9fe',
      secondary: '#ec4899',
      onSecondary: '#ffffff',
      secondaryContainer: '#fce7f3',
      background: '#fbf7ff',
      surface: '#f3e9fe',
      surfaceVariant: '#e9d8fc',
      text: '#1e1b4b',
      textMuted: '#6f6699',
      border: '#dcc4f7',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#a78bfa',
      onPrimary: '#4c1d95',
      primaryContainer: '#5b21b6',
      secondary: '#f472b6',
      onSecondary: '#831843',
      secondaryContainer: '#9f1239',
      background: '#1e1b4b',
      surface: '#312e81',
      surfaceVariant: '#3730a3',
      text: '#f5f3ff',
      textMuted: '#a5b4fc',
      border: '#4338ca',
      ...STATUS_DARK,
    },
  },
  slate: {
    name: 'slate',
    label: 'Corporativo',
    icon: 'briefcase',
    description:
      'Color seleccionado para apps corporativas: negocios, productividad, B2B y paneles. Grises sobrios y profesionales.',
    light: {
      primary: '#334155',
      onPrimary: '#ffffff',
      primaryContainer: '#e2e8f0',
      secondary: '#3b82f6',
      onSecondary: '#ffffff',
      secondaryContainer: '#dbeafe',
      background: '#f7f9fc',
      surface: '#eef2f8',
      surfaceVariant: '#e2e8f2',
      text: '#0f172a',
      textMuted: '#5b6b82',
      border: '#cfd8e6',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#cbd5e1',
      onPrimary: '#0f172a',
      primaryContainer: '#334155',
      secondary: '#60a5fa',
      onSecondary: '#0c2a6b',
      secondaryContainer: '#1e40af',
      background: '#020617',
      surface: '#0f172a',
      surfaceVariant: '#1e293b',
      text: '#f8fafc',
      textMuted: '#94a3b8',
      border: '#1e293b',
      ...STATUS_DARK,
    },
  },
  mono: {
    name: 'mono',
    label: 'Editorial',
    icon: 'newspaper-variant',
    description:
      'Color seleccionado para apps editoriales: noticias, lectura, blogs y portfolios. Escala de grises minimalista y elegante.',
    light: {
      primary: '#18181b',
      onPrimary: '#fafafa',
      primaryContainer: '#e4e4e7',
      secondary: '#52525b',
      onSecondary: '#fafafa',
      secondaryContainer: '#d4d4d8',
      background: '#fafafa',
      surface: '#f4f4f5',
      surfaceVariant: '#e9e9ec',
      text: '#09090b',
      textMuted: '#71717a',
      border: '#dcdce0',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#fafafa',
      onPrimary: '#18181b',
      primaryContainer: '#27272a',
      secondary: '#d4d4d8',
      onSecondary: '#18181b',
      secondaryContainer: '#3f3f46',
      background: '#09090b',
      surface: '#18181b',
      surfaceVariant: '#27272a',
      text: '#fafafa',
      textMuted: '#a1a1aa',
      border: '#27272a',
      ...STATUS_DARK,
    },
  },
  emerald: {
    name: 'emerald',
    label: 'Comercio',
    icon: 'store',
    description:
      'Color seleccionado para apps de comercio: e-commerce, ofertas, checkout y retail. Verde esmeralda (verde dinero) que transmite confianza al comprar.',
    light: {
      primary: '#059669',
      onPrimary: '#ffffff',
      primaryContainer: '#d1fae5',
      secondary: '#047857',
      onSecondary: '#ffffff',
      secondaryContainer: '#a7f3d0',
      background: '#f3fdf9',
      surface: '#e3f7ee',
      surfaceVariant: '#c9efdd',
      text: '#022c22',
      textMuted: '#5a7a6e',
      border: '#b3e6cf',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#34d399',
      onPrimary: '#022c22',
      primaryContainer: '#065f46',
      secondary: '#6ee7b7',
      onSecondary: '#022c22',
      secondaryContainer: '#047857',
      background: '#0a1f17',
      surface: '#11271f',
      surfaceVariant: '#1c3a2e',
      text: '#ecfdf5',
      textMuted: '#86a99b',
      border: '#1c3a2e',
      ...STATUS_DARK,
    },
  },
  teal: {
    name: 'teal',
    label: 'Bienestar',
    icon: 'spa',
    description:
      'Color seleccionado para apps de bienestar: salud, wellness, meditación y fitness. Verdes azulados serenos y premium.',
    light: {
      primary: '#0d9488',
      onPrimary: '#ffffff',
      primaryContainer: '#ccfbf1',
      secondary: '#059669',
      onSecondary: '#ffffff',
      secondaryContainer: '#d1fae5',
      background: '#f2fdfb',
      surface: '#e2f7f2',
      surfaceVariant: '#caefe8',
      text: '#0f172a',
      textMuted: '#5a7a74',
      border: '#b3e3da',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#2dd4bf',
      onPrimary: '#042f2e',
      primaryContainer: '#0f766e',
      secondary: '#34d399',
      onSecondary: '#022c22',
      secondaryContainer: '#047857',
      background: '#0f172a',
      surface: '#1e293b',
      surfaceVariant: '#163832',
      text: '#f1f5f9',
      textMuted: '#94a3b8',
      border: '#334155',
      ...STATUS_DARK,
    },
  },
  volt: {
    name: 'volt',
    label: 'Deporte',
    icon: 'run-fast',
    description:
      'Color seleccionado para apps de deporte: fitness, running, esports y marcadores en vivo. Índigo eléctrico con acento lima que transmite energía y acción.',
    light: {
      primary: '#4f46e5',
      onPrimary: '#ffffff',
      primaryContainer: '#e0e7ff',
      secondary: '#65a30d',
      onSecondary: '#ffffff',
      secondaryContainer: '#ecfccb',
      background: '#f6f7ff',
      surface: '#eaecfe',
      surfaceVariant: '#dadefb',
      text: '#1e1b4b',
      textMuted: '#5b5f86',
      border: '#c7ccf6',
      ...STATUS_LIGHT,
    },
    dark: {
      primary: '#818cf8',
      onPrimary: '#1e1b4b',
      primaryContainer: '#3730a3',
      secondary: '#a3e635',
      onSecondary: '#1a2e05',
      secondaryContainer: '#3f6212',
      background: '#14132b',
      surface: '#20203f',
      surfaceVariant: '#2c2b50',
      text: '#eef2ff',
      textMuted: '#a5b4fc',
      border: '#2c2b50',
      ...STATUS_DARK,
    },
  },
};

export const PALETTE_NAMES = Object.keys(PALETTES) as PaletteName[];
